In [1]:

import numpy as np

In [29]:
#1-d Array
arr1=np.array([1,2,3,4,5])

In [ ]:
arr1

array([1, 2, 3, 4, 5])

In [ ]:
type(arr1)

numpy.ndarray

In [30]:
print(arr1.ndim)

1


In [ ]:
#2-d Array
arr2=np.array([[1,2,3],[4,5,6]])

In [ ]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
print(arr2.ndim)

2


In [ ]:
arr3=np.zeros((2,3))

In [ ]:
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
print(arr3.ndim)

2


In [ ]:
type(arr3)

numpy.ndarray

In [ ]:
arr4=np.ones((3,3))

In [ ]:
arr4

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
# 0-d Array
arr=np.array(55)
arr

array(55)

In [ ]:
# Accessing Array Elements
arr1=np.array([1,2,3,4,5])
print(arr1[0])

1


In [ ]:
arr1[3]

4

In [31]:
arr2=np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
#2nd element on 1st row
arr2[0,1]

2

In [ ]:
arr2[1]

array([4, 5, 6])

In [ ]:
arr2[1,1]

5

In [ ]:
import numpy as np
arr3 = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr3[1:5])

[2 3 4 5]


In [ ]:
arr4 = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr4[4:])

[5 6 7]


In [ ]:
arr5 = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr5[:4])

[1 2 3 4]


In [ ]:
arr6 = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr6[-3:-1])

[5 6]


In [ ]:
#Return every other element from index 1 to index 5:
arr7 = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr7[1:5:2])

[2 4]


In [ ]:
# Shape
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr.shape)

(2, 4)


In [ ]:
#Reshape From 1-D to 2-D
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
# Reshape From 1-D to 3-D
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(2, 3, 2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [ ]:
# Iterating Arrays
arr = np.array([1, 2, 3])
for x in arr:
  print(x)

1
2
3


In [ ]:
# Iterate on the elements of the following 2-D array:
arr = np.array([[1, 2, 3], [4, 5, 6]])
for x in arr:
  print(x)

[1 2 3]
[4 5 6]


In [ ]:
# NumPy Joining Array
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.concatenate((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


In [ ]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr = np.concatenate((arr1, arr2),axis=1)
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
# Join two 2-D arrays along rows (axis=1):
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr = np.concatenate((arr1, arr2), axis=1)
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
#Splitting NumPy Arrays
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 3)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 4)
print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [ ]:
# Random Number
from numpy import random
x = random.randint(100)
print(x)

99


In [ ]:
#rand() method returns a random float between 0 and 1.
from numpy import random
x = random.rand()
print(x)

0.33617662216902333


In [ ]:
# Generate Random Array
from numpy import random
x=random.randint(100, size=(5))
print(x)

[16 49 97 46 21]


In [ ]:
# A 2-D array with 3 rows, each row containing 5 random integers from 0 to 100:
from numpy import random
x = random.randint(100, size=(3, 5))
print(x)

[[33 74 52 39 79]
 [79 56 75 77 19]
 [62 20 44 22 32]]


In [ ]:
# Generate a 1-D array containing 5 random floats:
from numpy import random
x = random.rand(5)
print(x)

[0.00877499 0.51692795 0.68280874 0.39859247 0.84708966]


In [ ]:
# Generate a 2-D array with 3 rows, each row containing 5 random numbers:
from numpy import random
x = random.rand(3, 5)
print(x)

[[0.50992462 0.80351243 0.06195126 0.05353849 0.51009177]
 [0.14751058 0.72730099 0.64699429 0.18474997 0.52198649]
 [0.84128904 0.10500631 0.6827765  0.07272668 0.82578797]]
